travis:
  secure:
    BINSTAR_TOKEN: GbKM9WUfX+ByOUB+ZjGVv1T+FwHW4qkpgp9Sw03JdBBZVluWmqbmaVNWdaYPcy6b4GGbtHCe8omejw03JF+pJ2sLwhZbx+FpmGivOHdXLgy8hu0UwHkXK4FbY4OVFlN1t0T1GyOYOnofwSvdgC6dMupGq9vweOGhJRyb9WGk6qAt6BF4XdO8oJ2FbcXi5lPeJTHMUtzX1e4Oi50VCfrxJMY+Ims8Mpijx37/f9YzA0yVh9t6rBrSN+SEsHtZAV0UbSJp2U0ZfLzBVuw5XceFx5orLEpYZWewoX8A71sVpqZRuk3YjKbhpile/PTn5AtZGU/LUyedhghukTmfqlZx8H1WGt1fJ8mijn0n5Bi3S9zrhI6m7qJO6ZLVVi6o9s4KGxBEKreNC7AxLzWClPb+vUvK3lbInuVYYhrQuDR3hQ2JGCaO3oNdv1ORJW/poJ4rPNf7Yo1mVl/f7+aE4TzV3Sg5EXhUKLhy918c4/bxwQ7ECl8Xh/xpCbxWePHzVPyixQreIRl/RegLohx14pTYWOOIkIjzCDyzsdYWXGOihk4nWx7pCyKLuRqYnhlDxaDosVZJhfb8sOogtKkldifzTZVlw0vOcFmxAXgmQYsjdpekQ+4IqihgdBVhvRndl78o3pHZYxinfDqPvLgk+qcUIE8znvOOVZLxfYFX8mX74Q4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
